application: bucksbuddy-123
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:       # static then dynamic

- url: /_ah/spi/.*
  script: bucksbuddy.api
  secure: always

libraries:

- name: webapp2
  version: latest

- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest
