application: bucks-buddy
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:       # static then dynamic

- url: /_ah/spi/.*
  script: bucksbuddy.api

- url: /
  static_files: easeon1/mainpage.html
  upload: easeon1/mainpage.html

libraries:

- name: webapp2
  version: latest

- name: endpoints
  version: latest

# pycrypto library used for OAuth2 (req'd for authenticated APIs)
- name: pycrypto
  version: latest
